import json
from typing import List, Dict, Any, AsyncGenerator
from llama_index.core import get_response_synthesizer
from llama_index.core.schema import TextNode
from llama_index.llms.ollama import Ollama

class LlamaIndexSynthesizer:
    def __init__(self, model_name: str = "mistral", timeout: float = 360.0):
        """
        Initializes the local LLM and the LlamaIndex synthesizer.
        """
        self.llm = Ollama(model=model_name, request_timeout=timeout)
        
        # Configure for streaming and asynchronous execution
        self.synthesizer = get_response_synthesizer(
            llm=self.llm,
            response_mode="tree_summarize",
            streaming=True,
            use_async=True
        )

    def _flatten_to_nodes(self, raw_data: List[Dict[str, Any]]) -> List[TextNode]:
        """
        Converts a list of JSON dictionaries into LlamaIndex TextNodes.
        Uses a basic flattening approach to save tokens.
        """
        nodes = []
        for item in raw_data:
            # Flatten 1 level deep. Adjust this if your JSON is deeply nested.
            flat_text = "\n".join([f"{k}: {json.dumps(v)}" for k, v in item.items()])
            nodes.append(TextNode(text=flat_text))
        return nodes

    async def stream_synthesis(self, query: str, raw_data: List[Dict[str, Any]]) -> AsyncGenerator[str, None]:
        """
        Takes the user query and raw MCP data, runs the synthesis tree,
        and yields text chunks as they are generated by Ollama.
        """
        if not raw_data:
            yield "No data returned from the tools to synthesize."
            return

        # 1. Convert raw JSON to nodes
        nodes = self._flatten_to_nodes(raw_data)

        # 2. Trigger the asynchronous synthesis
        streaming_response = await self.synthesizer.asynthesize(
            query=query,
            nodes=nodes
        )

        # 3. Yield the text chunks as they arrive
        async for text_chunk in streaming_response.async_response_gen():
            yield text_chunk
