import json
from typing import List, Dict, Any, AsyncGenerator
from llama_index.core import get_response_synthesizer
from llama_index.core.schema import TextNode, NodeWithScore
from llama_index.llms.ollama import Ollama

class LlamaIndexSynthesizer:
    def __init__(self, model_name: str = "mistral", timeout: float = 360.0):
        """
        Initializes the local LLM and the LlamaIndex synthesizer.
        """
        # 1. Initialize the local Ollama connection
        self.llm = Ollama(model=model_name, request_timeout=timeout)
        
        # 2. Configure the synthesizer for async streaming
        self.synthesizer = get_response_synthesizer(
            llm=self.llm,
            response_mode="tree_summarize",
            streaming=True,
            use_async=True
        )

    def _flatten_to_nodes(self, raw_data: Any) -> List[NodeWithScore]:
        """
        Converts raw data into LlamaIndex Nodes.
        Includes safety checks for raw JSON strings and wraps them in NodeWithScore.
        """
        nodes = []
        
        # Check 1: If the MCP tool returned a single raw string, parse it to JSON
        if isinstance(raw_data, str):
            try:
                raw_data = json.loads(raw_data)
            except json.JSONDecodeError:
                # If it is just a normal string, wrap it and return early
                text_node = TextNode(text=raw_data)
                return [NodeWithScore(node=text_node, score=1.0)]

        # Check 2: If parsing resulted in a single dictionary, wrap it in a list
        if isinstance(raw_data, dict):
            raw_data = [raw_data]

        # Check 3: Ensure we are working with a list, then flatten each item
        if isinstance(raw_data, list):
            for item in raw_data:
                if isinstance(item, dict):
                    # Safely iterate over the dictionary items
                    flat_text = "\n".join([f"{k}: {json.dumps(v)}" for k, v in item.items()])
                    text_node = TextNode(text=flat_text)
                    nodes.append(NodeWithScore(node=text_node, score=1.0))
                    
                elif isinstance(item, str):
                    # Try to parse strings inside the list
                    try:
                        parsed_item = json.loads(item)
                        if isinstance(parsed_item, dict):
                            flat_text = "\n".join([f"{k}: {json.dumps(v)}" for k, v in parsed_item.items()])
                            text_node = TextNode(text=flat_text)
                            nodes.append(NodeWithScore(node=text_node, score=1.0))
                        else:
                            text_node = TextNode(text=str(parsed_item))
                            nodes.append(NodeWithScore(node=text_node, score=1.0))
                    except json.JSONDecodeError:
                        text_node = TextNode(text=item)
                        nodes.append(NodeWithScore(node=text_node, score=1.0))
                else:
                    # Fallback for booleans, ints, or unexpected types
                    text_node = TextNode(text=str(item))
                    nodes.append(NodeWithScore(node=text_node, score=1.0))
                    
        return nodes

    async def stream_synthesis(self, query: str, raw_data: Any) -> AsyncGenerator[str, None]:
        """
        Takes the user query and raw MCP data, formats the data into nodes,
        runs the synthesis tree, and yields text chunks generated by Ollama.
        """
        if not raw_data:
            yield "No data returned from the tools to synthesize."
            return

        # 1. Convert raw JSON/strings to LlamaIndex NodeWithScore objects
        nodes = self._flatten_to_nodes(raw_data)

        if not nodes:
            yield "Could not parse the data from the tools into a readable format."
            return

        # 2. Trigger the asynchronous synthesis with the original user query
        streaming_response = await self.synthesizer.asynthesize(
            query=query,
            nodes=nodes
        )

        # 3. Yield the text chunks as they arrive from Ollama
        async for text_chunk in streaming_response.async_response_gen():
            yield text_chunk
